#!/usr/bin/env python
"""One-time ingest of scraped SharePoint data into OpenAssist."""
import json, requests as req

data = [
    {"title": "P20260206005 5500383 Mag Glycinate 250mg + Creatine Monohydrate 5000mg Unflavored DDR MBR for Natures Wonder", "urgency": "High", "status": "In Progress", "requestor": "Chris Enlow", "date_requested": "2/16/2026", "type": "Bulk Formula Uploads", "requested_completion": "2/19/2026", "instructions": "P20260206005 5500383 Mag Glycinate 250mg + Creatine Monohydrate 5000mg Unflavored MBR for Natures Wonder.", "assigned_to": "Tina Willis"},
    {"title": "Change buyer description to INTERNAL, for item IN900962 ORG DDR", "urgency": "Medium", "status": "In Progress", "requestor": "Troy Gantt", "date_requested": "1/14/2026", "type": "Special Requests", "requested_completion": "1/16/2026", "instructions": "Change buyer description to INTERNAL, for item IN900962 ORG DDR", "assigned_to": "Tina Willis"},
    {"title": "Change the vendor name from PARADIGM PACKAGING / DBA COMAR to Tricor", "urgency": "High", "status": "MDM Placed On Hold", "requestor": "Troy Gantt", "date_requested": "1/14/2026", "type": "Special Requests", "requested_completion": "1/15/2026", "instructions": "Change the vendor name from PARADIGM PACKAGING / DBA COMAR to Tricor. Pending part number to update. Otherwise this request will be cancelled.", "assigned_to": "Tina Willis"},
    {"title": "520136 Vit C 1000mg + Bioflavonoids Version 804 MBR", "urgency": "High", "status": "Not Started", "requestor": "Chris Enlow", "date_requested": "2/17/2026", "type": "BOM Updates", "requested_completion": "2/19/2026", "instructions": "520136 Vit C 1000mg + Bioflavonoids Version 804 MBR. Refer to Aubrey Giacopelli and Adam Saintz to set up routers.", "assigned_to": "Tina Willis"},
    {"title": "WAL653192 LABEL LP145886 STATUS CHANGE FROM DISC TO APPROVE", "urgency": "High", "status": "Not Started", "requestor": "Theresa Masarik", "date_requested": "2/17/2026", "type": "BOM Updates", "requested_completion": "2/17/2026", "instructions": "PLEASE CHANGE THE STATUS OF LABEL LP145886 IN THE BOM OF WAL653192 FROM DISC TO APPROVE. - THANK YOU", "assigned_to": "Tina Willis"},
    {"title": "P20250730002 5500305H Krill Oil 500mg MBR for NOW Foods", "urgency": "High", "status": "Not Started", "requestor": "Chris Enlow", "date_requested": "2/19/2026", "type": "Bulk Formula Uploads", "requested_completion": "2/24/2026", "instructions": "P20250730002 5500305H Krill Oil 500mg MBR for NOW Foods.", "assigned_to": ""},
    {"title": "P20250730001 5500304H Krill Oil 1000mg MBR for NOW Foods", "urgency": "High", "status": "Not Started", "requestor": "Chris Enlow", "date_requested": "2/19/2026", "type": "Bulk Formula Uploads", "requested_completion": "2/24/2026", "instructions": "P20250730001 5500304H Krill Oil 1000mg MBR for NOW Foods.", "assigned_to": ""},
    {"title": "HL FG status change - transition to DISC", "urgency": "Low", "status": "Not Started", "requestor": "Evanne Adams", "date_requested": "2/19/2026", "type": "Status Change Requests", "requested_completion": "2/24/2026", "instructions": "Please change the HL FG status from TRANSITION to DISC: HLL56326-13 HLL14235-07 HLL44811-09 HLL14228-11", "assigned_to": ""},
    {"title": "GNC653802", "urgency": "Medium", "status": "Not Started", "requestor": "Jordan Buffington", "date_requested": "2/5/2026", "type": "BOM Updates", "requested_completion": "2/19/2026", "instructions": "Please add the below comment to GNC653802: GNC653802 (213533) - AMP Training VP 30CT Each packet contains 7 components. Pallet Config: 6 shippers per layer x 7 layers", "assigned_to": ""},
    {"title": "HLL37211-16 Update Pallet Configuration", "urgency": "Medium", "status": "Not Started", "requestor": "Jordan Buffington", "date_requested": "2/6/2026", "type": "BOM Updates", "requested_completion": "2/20/2026", "instructions": "Please update cases/layer to 9", "assigned_to": ""},
    {"title": "GNC653818 Comments", "urgency": "Medium", "status": "Not Started", "requestor": "Jordan Buffington", "date_requested": "2/6/2026", "type": "BOM Updates", "requested_completion": "2/20/2026", "instructions": "Please add the below comment to GNC653818: GNC653818 (221533) - PRO PERFORMANCE VP 30CT. Pallet Config: 6 shippers per layer x 7 layers", "assigned_to": ""},
    {"title": "LP145595 Primary Vendor Update", "urgency": "Medium", "status": "Not Started", "requestor": "Justin Westervelt", "date_requested": "2/9/2026", "type": "Special Requests", "requested_completion": "2/13/2026", "instructions": "Please update the Primary Vendor to MULTI PACKAGING SOLUTIONS for this label in the AND org.", "assigned_to": ""},
    {"title": "358642", "urgency": "Medium", "status": "Not Started", "requestor": "Mauricio Agudelo", "date_requested": "2/10/2026", "type": "Miscellaneous Requests", "requested_completion": "2/12/2026", "instructions": "Please update the rounding multiple of 358642 to 25kg. DDR", "assigned_to": ""},
    {"title": "TOP649972 Pallet Configuration Update", "urgency": "Medium", "status": "Not Started", "requestor": "Jordan Buffington", "date_requested": "2/10/2026", "type": "BOM Updates", "requested_completion": "2/24/2026", "instructions": "Please updated the pallet configuration to 13/7.", "assigned_to": ""},
    {"title": "IVCN items - Change item status from APPROVED to TRANSITION", "urgency": "Medium", "status": "Not Started", "requestor": "Sonya Taylor", "date_requested": "2/10/2026", "type": "Status Change Requests", "requested_completion": "2/17/2026", "instructions": "Please change the item status for the following from APPROVED to TRANSITION: WAL652290N WAL652293N WAL652447N WAL652457N WAL652487N WAL652611N WAL653149N WAL653189N", "assigned_to": ""},
    {"title": "Change item status for WAL653211N from TRANSITION TO APPROVED", "urgency": "Medium", "status": "Not Started", "requestor": "Sonya Taylor", "date_requested": "2/10/2026", "type": "Status Change Requests", "requested_completion": "2/16/2026", "instructions": "Change item status for WAL653211N from TRANSITION TO APPROVED", "assigned_to": ""},
    {"title": "Buyer / Planner Updates", "urgency": "Medium", "status": "Not Started", "requestor": "Stephen Kester", "date_requested": "2/11/2026", "type": "Miscellaneous Requests", "requested_completion": "2/13/2026", "instructions": "Please update the below buyer / planner codes. 359464 - RM-1 RM3300846 - RM-2 RM3300635 - RM-2 RM3300667 - RM-1 RM1918 - RM-2", "assigned_to": ""},
    {"title": "358122", "urgency": "Medium", "status": "Not Started", "requestor": "Stephanie Montoya", "date_requested": "2/11/2026", "type": "Miscellaneous Requests", "requested_completion": "2/12/2026", "instructions": "Please update quantity to 400 MOQ for DDR org.", "assigned_to": ""},
    {"title": "GNI update label to BOM", "urgency": "Medium", "status": "Not Started", "requestor": "Faith LePage", "date_requested": "2/12/2026", "type": "BOM Updates", "requested_completion": "2/13/2026", "instructions": "Please update the BOM updated with LP146121, and DISCO LP145937. This is for PO IND0110024 / SO# 1068452", "assigned_to": ""},
    {"title": "Buyer/Planner code updates for Amazon items coming from IVCN", "urgency": "Medium", "status": "Not Started", "requestor": "Sonya Taylor", "date_requested": "2/13/2026", "type": "Status Change Requests", "requested_completion": "2/20/2026", "instructions": "Please update the buyer & planner codes from IVC to WAL-P for the following items: IVC653377N IVC653696N IVC653764N IVC653765N IVC653766N", "assigned_to": ""},
    {"title": "Please update this item's MOQ to 3,500- PM0180 for the AND org.", "urgency": "Medium", "status": "Not Started", "requestor": "Olivia Griffiths", "date_requested": "2/16/2026", "type": "Special Requests", "requested_completion": "2/17/2026", "instructions": "Please update this item's MOQ to 3,500- PM0180 for the AND org.", "assigned_to": ""},
    {"title": "3300306", "urgency": "Medium", "status": "Not Started", "requestor": "Mauricio Agudelo", "date_requested": "2/17/2026", "type": "Miscellaneous Requests", "requested_completion": "2/19/2026", "instructions": "Please update the rounding multiple to 25kg and the MOQ to 50kg of 3300306. DDR", "assigned_to": ""},
    {"title": "Please update this item's LT to 10 days for the AND and DDR org- PQ409706.", "urgency": "Medium", "status": "Not Started", "requestor": "Olivia Griffiths", "date_requested": "2/17/2026", "type": "Special Requests", "requested_completion": "2/18/2026", "instructions": "Please update this item's LT to 10 days for the AND and DDR org- PQ409706.", "assigned_to": ""},
    {"title": "3300228", "urgency": "Medium", "status": "Not Started", "requestor": "Mauricio Agudelo", "date_requested": "2/18/2026", "type": "Vendor MOQ Updates", "requested_completion": "2/20/2026", "instructions": "Please updated the MOQ and rounding multiple of 3300228 to 25kg. DDR", "assigned_to": ""},
    {"title": "Please update this item, PQ409628, to COMPDIS Planner and Buyer Description for the AND org.", "urgency": "Medium", "status": "Not Started", "requestor": "Olivia Griffiths", "date_requested": "2/18/2026", "type": "Special Requests", "requested_completion": "2/19/2026", "instructions": "Please update this item, PQ409628, to COMPDIS Planner and Buyer Description for the AND org.", "assigned_to": ""},
    {"title": "TOP649935 Pallet Update", "urgency": "Medium", "status": "Not Started", "requestor": "Jordan Buffington", "date_requested": "2/19/2026", "type": "BOM Updates", "requested_completion": "3/5/2026", "instructions": "Please update the layers per pallet to 7.", "assigned_to": ""},
]

resp = req.post("http://127.0.0.1:5001/api/mdm/ingest", json={
    "api_key": "openassist-ingest-2026",
    "requests": data
})
print(f"Status: {resp.status_code}")
print(json.dumps(resp.json(), indent=2))
